Repository Agarwalvidu/ArdhNaariShakti_Taara_Frontend, pull requests merged in 2025-07, with the labels that each got.

#55 UPDATE: flip card image updated
  public/images/category/card_image.jpg
  src/components/donation/Donation.jsx
Labels: enhancement, gssoc-25, level-1

#59 Create Expand job Column
  Expand job Column
Labels: gssoc-25, level-1

#77 Enhancement: Jobs Page Revamp (#69)
  README.MD
  src/pages/jobs/jobs.css
  src/pages/jobs/jobs.jsx
Labels: gssoc-25, level-2

#80 Fix: Added navigation links between Register and Login pages (#20)
  src/pages/login/Login.jsx
  src/pages/login/Regsiter.jsx
Labels: gssoc-25, level-1
