Repository Agarwalvidu/ArdhNaariShakti_Taara_Frontend, pull requests merged in 2025-08, with the labels that each got.

#84 Fix header
  src/components/header/Header.jsx
  src/components/header/header.css
Labels: gssoc-25, level-1

#86 Made login page fully responsive for all screen sizes
  src/pages/login/login.css
Labels: gssoc-25, level-1

#67 Improve UI for login and registration pages
  src/assets/images/my-account.jpg
  src/pages/login/Login.jsx
  src/pages/login/Regsiter.jsx
  src/pages/login/login.css
Labels: gssoc-25, level-1

#157 issue#151
  src/App.js
  src/pages/about/About.jsx
  src/pages/about/about.css
Labels: gssoc-25, level-2

#159 Link Footer "Resources" Section: Help Page #152
  src/App.js
  src/pages/help/Help.jsx
  src/pages/help/help.css
Labels: gssoc-25, level-2

#160 Link Footer "Resources" Section: Terms & Conditions Page #153
  src/App.js
  src/pages/terms/Terms.jsx
  src/pages/terms/terms.css
Labels: gssoc-25, level-2

#163 In footer's Contact Us section, Change the credentials #133
  src/App.js
  src/pages/contact/Contact.jsx
  src/pages/contact/contact.css
Labels: gssoc-25, level-2

#166 Fixed Issue #101: Updated the README of the project.
  README.MD
Labels: gssoc-25, level-1

#165 Add a section on blogs page to add a new post if logged in #132
  src/components/blog/Card.jsx
  src/components/blog/blog.css
Labels: gssoc-25, level-2

#198 #141 : UI Improvements on Shelter Page , fixed
  src/pages/shelter/shelter.css
  src/pages/shelter/shelter.jsx
Labels: gssoc-25, level-1

#200 Fix: Align text and spacing for homepage cards (Taara Bot, Blogs, She…
  src/components/HomeCards/InfoElements.js
Labels: gssoc-25, level-1

#201 addition of Code of conduct file
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-25, level-1

#195 Fix/real time editor
  package-lock.json
  package.json
  src/components/create/Create.jsx
  src/components/create/RTE.jsx
  src/components/create/create.css
  src/pages/contact/Contact.jsx
Labels: gssoc-25, level-3

#211 helloo
  src/components/donation/Donation.css
Labels: gssoc-25, level-1

#111 ✨ Added "Calming Corner" Section with Guided Audio & Soundscapes for Mental Wellness
  build/asset-manifest.json
  build/images/category/card_image.jpg
  build/static/css/main.2f7f77e2.css.css
  build/static/js/main.cc5536a6.js.LICENSE.txt.txt
  build/static/media/music.cb242286676fe9a5270f.png
  src/App.js
  src/assets/data/data.js
  src/assets/images/music.png
  src/components/HomeCards/InfoElements.js
  src/components/HomeCards/index.js
  src/pages/music/CalmingCorner.jsx
  src/pages/music/calmingCorner.css
Labels: gssoc-25, level-3

#216 Enhance Job Listings page with search, filters, remote toggle, and so…
  src/pages/jobs/jobs.css
  src/pages/jobs/jobs.jsx
Labels: gssoc-25, level-3

#173 Not found page
  src/App.js
  src/pages/contact/Contact.jsx
  src/pages/notfound/notfound.css
  src/pages/notfound/page.jsx
Labels: gssoc-25, level-3

#218 Fix#205-resources-links-updated
  src/components/footer/Footer.jsx
Labels: gssoc-25, level-1

#181 auto slide-functionality
  src/components/category/Category.jsx
  src/pages/contact/Contact.jsx
Labels: gssoc-25, level-1

#226 feat- Add "Forgot Password" Functionality
  src/App.js
  src/pages/login/ForgotPassword.jsx
  src/pages/login/Login.jsx
Labels: gssoc-25, level-2

#229 About Page UI improvements
  src/pages/about/About.jsx
  src/pages/about/about.css
Labels: gssoc-25, level-2

#237 UI change in contact page
  src/pages/contact/Contact.jsx
  src/pages/contact/contact.css
Labels: gssoc-25, level-1

#240 Text correction Job(s)
  src/assets/data/data.js
Labels: gssoc-25, level-1

#244 Adjust Heading Size for "ArdhNaariShakti Taara"
  src/components/header/header.css
Labels: gssoc-25, level-2

#261 gssoc/animated nav and sidebar
  package-lock.json
  package.json
  src/components/header/Header.jsx
  src/components/header/header.css
Labels: gssoc25, level-2
